import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    // EXTRAÇÃO DE PARÂMETROS DO CORPO DA REQUISIÇÃO
    const { pdfBase64, pdfFileName, extractedData, language } =
      await request.json();

    // VALIDAÇÃO DE DADOS
    if (!pdfBase64 || !pdfFileName) {
      return NextResponse.json({ message: "Missing PDF data" }, { status: 400 });
    }

    // CONFIGURAÇÃO MAILGUN
    const MAILGUN_API_KEY = process.env.MAILGUN_API_KEY;
    const MAILGUN_DOMAIN =
      process.env.MAILGUN_DOMAIN || process.env.EMAIL_FROM?.split("@")[1];

    if (!MAILGUN_API_KEY || !MAILGUN_DOMAIN || !process.env.EMAIL_FROM) {
      return NextResponse.json(
        {
          message:
            "Mailgun is not configured. Set MAILGUN_API_KEY, MAILGUN_DOMAIN, and EMAIL_FROM in .env.local.",
        },
        { status: 500 }
      );
    }

    // PREPARAÇÃO DO ASSUNTO E CONTEÚDO DO EMAIL
    const isPortuguese = language === "pt";
    const subject = isPortuguese
      ? `Novo Documento da Techlab - ${new Date().toLocaleDateString("pt-PT")}`
      : `New Techlab Document - ${new Date().toLocaleDateString("en-US")}`;

    const htmlContent = isPortuguese
      ? `
        <h2>Novo Documento Submetido</h2>
        <p>Um novo documento foi gerado e enviado através do chat-bot da Techlab.</p>
        ${
          extractedData
            ? `
          <h3>Detalhes do Documento:</h3>
          <p><strong>Informações Extraídas:</strong></p>
          <pre>${JSON.stringify(extractedData, null, 2)}</pre>
        `
            : ""
        }
        <p><strong>Nome do Ficheiro:</strong> ${pdfFileName}</p>
        <p>Por favor, reveja o documento em anexo.</p>
        <hr>
        <p><em>Este é um email automático gerado pelo chat-bot da Techlab.</em></p>
      `
      : `
        <h2>New Document Submitted</h2>
        <p>A new document has been generated and sent through the Techlab chat-bot.</p>
        ${
          extractedData
            ? `
          <h3>Document Details:</h3>
          <p><strong>Extracted Information:</strong></p>
          <pre>${JSON.stringify(extractedData, null, 2)}</pre>
        `
            : ""
        }
        <p><strong>File Name:</strong> ${pdfFileName}</p>
        <p>Please review the attached document.</p>
        <hr>
        <p><em>This is an automated email generated by the Techlab chat-bot.</em></p>
      `;

    // PREPARAÇÃO DO FORMULÁRIO MAILGUN COM ANEXO
    const pdfBuffer = Buffer.from(pdfBase64, "base64");

    const mgUrl = `https://api.mailgun.net/v3/${MAILGUN_DOMAIN}/messages`;
    const auth = `Basic ${Buffer.from(`api:${MAILGUN_API_KEY}`).toString("base64")}`;

    const formData = new FormData();
    formData.append("from", process.env.EMAIL_FROM);
    formData.append("to", "joaoajorge@ua.pt");
    formData.append("subject", subject);
    formData.append("html", htmlContent);

    // ADIAÇÃO DO PDF COMO BLOB
    const pdfBlob = new Blob([pdfBuffer], { type: "application/pdf" });
    formData.append("attachment", pdfBlob, pdfFileName);

    // ENVIO VIA MAILGUN
    const res = await fetch(mgUrl, {
      method: "POST",
      headers: {
        Authorization: auth,
      },
      body: formData as any,
    });

    if (!res.ok) {
      const text = await res.text();
      console.error("Mailgun error response:", res.status, text);
      return NextResponse.json(
        { message: `Mailgun error: ${res.status} ${text}` },
        { status: 500 }
      );
    }

    const bodyText = await res.text();
    console.log("Mailgun response:", bodyText);

    return NextResponse.json(
      {
        message: isPortuguese ? "Email enviado com sucesso" : "Email sent successfully",
        mailgun: bodyText,
      },
      { status: 200 }
    );
  } catch (error) {
    console.error("Email sending error:", error);
    const message = error instanceof Error ? error.message : "Unknown error occurred";
    return NextResponse.json({ message: `Failed to send email: ${message}` }, { status: 500 });
  }
}
