import { NextRequest, NextResponse } from "next/server";
import nodemailer from "nodemailer";

// Configure nodemailer transporter
const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_HOST,
  port: parseInt(process.env.EMAIL_PORT || "587"),
  secure: process.env.EMAIL_SECURE === "true",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASSWORD,
  },
});

export async function POST(request: NextRequest) {
  try {
    const {
      pdfBase64,
      pdfFileName,
      extractedData,
      language,
    } = await request.json();

    if (!pdfBase64 || !pdfFileName) {
      return NextResponse.json(
        { message: "Missing PDF data" },
        { status: 400 }
      );
    }

    // Prepare email content based on language
    const isPortuguese = language === "pt";
    const subject = isPortuguese
      ? `Novo Documento da Techlab - ${new Date().toLocaleDateString("pt-PT")}`
      : `New Techlab Document - ${new Date().toLocaleDateString("en-US")}`;

    const htmlContent = isPortuguese
      ? `
        <h2>Novo Documento Submetido</h2>
        <p>Um novo documento foi gerado e enviado através do Chat-Bot da Techlab.</p>
        ${
          extractedData
            ? `
          <h3>Detalhes do Documento:</h3>
          <p><strong>Informações Extraídas:</strong></p>
          <pre>${JSON.stringify(extractedData, null, 2)}</pre>
        `
            : ""
        }
        <p><strong>Nome do Ficheiro:</strong> ${pdfFileName}</p>
        <p>Por favor, reveja o documento em anexo.</p>
        <hr>
        <p><em>Este é um email automático gerado pelo Chat-Bot da Techlab.</em></p>
      `
      : `
        <h2>New Document Submitted</h2>
        <p>A new document has been generated and sent through the Techlab Chat-Bot.</p>
        ${
          extractedData
            ? `
          <h3>Document Details:</h3>
          <p><strong>Extracted Information:</strong></p>
          <pre>${JSON.stringify(extractedData, null, 2)}</pre>
        `
            : ""
        }
        <p><strong>File Name:</strong> ${pdfFileName}</p>
        <p>Please review the attached document.</p>
        <hr>
        <p><em>This is an automated email generated by the Techlab Chat-Bot.</em></p>
      `;

    // Convert base64 to buffer
    const pdfBuffer = Buffer.from(pdfBase64, "base64");

    // Send email
    const info = await transporter.sendMail({
      from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
      to: "joaoajorge@ua.pt", // Techlab email
      subject,
      html: htmlContent,
      attachments: [
        {
          filename: pdfFileName,
          content: pdfBuffer,
          contentType: "application/pdf",
        },
      ],
    });

    console.log("Email sent:", info.messageId);

    return NextResponse.json(
      {
        message: isPortuguese
          ? "Email enviado com sucesso"
          : "Email sent successfully",
        messageId: info.messageId,
      },
      { status: 200 }
    );
  } catch (error) {
    console.error("Email sending error:", error);

    const message =
      error instanceof Error ? error.message : "Unknown error occurred";

    return NextResponse.json(
      { message: `Failed to send email: ${message}` },
      { status: 500 }
    );
  }
}
