"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import { Message } from "@/utils/types";

interface GerarResumoBotComponentProps {
  messages: Message[];
  isPortugueseFlow: boolean;
}

interface ExtractedData {
  servico: string;
  contexto: string;
  prazoSolicitado: string;
  requisitoEspecificos: string;
  equipa: string;
  financiamento: string;
  empresa: string;
  contacto: string;
}

export default function GerarResumoBotComponent({ messages, isPortugueseFlow }: GerarResumoBotComponentProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = async () => {
    try {
      setIsGenerating(true);

      // Call the new API endpoint to extract data intelligently using Claude
      const extractResponse = await fetch("/api/extract-data", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages, isPortugueseFlow }),
      });

      if (!extractResponse.ok) {
        throw new Error(`Failed to extract data: ${extractResponse.status}`);
      }

      const { data }: { data: ExtractedData } = await extractResponse.json();

      // Create PDF using jsPDF
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      // Set fonts
      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(16);
      pdf.text("pci · creative science park tech lab", 105, 20, { align: "center" });

      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(14);
      pdf.text(isPortugueseFlow ? "Resumo Gerado pelo Chat-bot" : "Summary Generated by Chat-bot", 105, 30, { align: "center" });

      pdf.setFont("Helvetica", "normal");
      pdf.setFontSize(12);
      pdf.text(
        `${isPortugueseFlow ? "Pedido de" : "Request from"} ${data.empresa}`,
        105,
        38,
        { align: "center" }
      );

      // Table data
      const rows = [
        {
          categoria: isPortugueseFlow ? "Servico" : "Service",
          descricao: data.servico || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
        },
        {
          categoria: isPortugueseFlow ? "Contexto" : "Context",
          descricao: data.contexto || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
        },
        {
          categoria: isPortugueseFlow ? "Prazo Solicitado" : "Requested Timeline",
          descricao: data.prazoSolicitado || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
        },
        {
          categoria: isPortugueseFlow ? "Requisitos Especificos" : "Specific Requirements",
          descricao: data.requisitoEspecificos || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
        },
        {
          categoria: isPortugueseFlow ? "Equipa" : "Team",
          descricao: data.equipa || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
        },
        {
          categoria: isPortugueseFlow ? "Financiamento" : "Financing",
          descricao: data.financiamento || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
        },
        {
          categoria: isPortugueseFlow ? "Contacto" : "Contact",
          descricao: data.contacto || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
        },
      ];

      // Table styling
      const startY = 50;
      const col1Width = 50;
      const col2Width = 130;
      const rowHeight = 30;
      let currentY = startY;

      // Header
      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(10);
      pdf.text(isPortugueseFlow ? "Categoria" : "Category", 15, currentY + 8);
      pdf.text(isPortugueseFlow ? "Descricao" : "Description", 70, currentY + 8);
      pdf.line(15, currentY + 12, 200, currentY + 12);
      currentY += 20;

      // Rows
      pdf.setFont("Helvetica", "normal");
      pdf.setFontSize(9);
      rows.forEach((row) => {
        // Check if we need a new page
        if (currentY > 270) {
          pdf.addPage();
          currentY = 20;
        }

        // Category
        pdf.text(row.categoria, 15, currentY);

        // Description (with text wrapping)
        const descriptionLines = pdf.splitTextToSize(row.descricao, col2Width);
        pdf.text(descriptionLines, 70, currentY);

        // Calculate row height based on content
        const cellHeight = Math.max(10, descriptionLines.length * 6);
        currentY += cellHeight + 5;

        // Row separator
        pdf.line(15, currentY - 5, 200, currentY - 5);
      });

      // Save PDF
      pdf.save(`resumo_${data.empresa}.pdf`);
      setIsGenerating(false);
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert(isPortugueseFlow ? "Erro ao gerar o PDF" : "Error generating PDF");
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={generatePDF}
      disabled={isGenerating}
      className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition disabled:opacity-50 disabled:cursor-not-allowed"
    >
      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
      </svg>
      {isGenerating
        ? isPortugueseFlow
          ? "A gerar..."
          : "Generating..."
        : isPortugueseFlow
        ? "Descarregar resumo"
        : "Download summary"}
    </button>
  );
}
