"use client";

import { useState, useCallback } from "react";
import jsPDF from "jspdf";
import { Message } from "@/utils/types";
import ContactarEmailComponent from "./contactarEmailComponent";

interface GerarResumoBotComponentProps {
  messages: Message[];
  isPortugueseFlow: boolean;
  currentChatId?: string;
  onPDFGenerated?: (extractedData: ExtractedData) => void;
  onAskedForPDF?: (asked: boolean) => void;
  showConfirmation?: boolean;
  isGenerating?: boolean;
  pdfGenerated?: boolean;
  pdfExtractedData?: ExtractedData | null;
  onAddMessage?: (message: Message) => void;
}

export interface ExtractedData {
  servico: string;
  contexto: string;
  prazoSolicitado: string;
  requisitoEspecificos: string;
  equipa: string;
  financiamento: string;
  empresa: string;
  contacto: string;
}

export default function GerarResumoBotComponent({ 
  messages, 
  isPortugueseFlow,
  onPDFGenerated,
  currentChatId,
  onAskedForPDF,
  showConfirmation = false,
  isGenerating: externalIsGenerating = false,
  pdfGenerated: externalPdfGenerated = false,
  pdfExtractedData: externalPdfExtractedData = null,
  onAddMessage,
}: GerarResumoBotComponentProps) {
  const [isGenerating, setIsGenerating] = useState(externalIsGenerating);
  const [pdfExtractedData, setPdfExtractedData] = useState<ExtractedData | null>(externalPdfExtractedData);
  const [pdfBase64, setPdfBase64] = useState<string | null>(null);
  const [localPdfGenerated, setLocalPdfGenerated] = useState(externalPdfGenerated);

  const generatePDFDocument = useCallback(async (extractedData: ExtractedData) => {
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    // ASPETO DO PDF GERADO
    pdf.setFont("Helvetica", "bold");
    pdf.setFontSize(16);
    pdf.text("pci · creative science park tech lab", 105, 20, { align: "center" });

    pdf.setFont("Helvetica", "bold");
    pdf.setFontSize(14);
    pdf.text(isPortugueseFlow ? "Resumo Gerado pelo Chatbot" : "Summary Generated by Chat-bot", 105, 30, { align: "center" });
    pdf.setFontSize(12);
    pdf.text(
      `${isPortugueseFlow ? "Pedido de" : "Request from"} ${extractedData.empresa}`,
      105,
      38,
      { align: "center" }
    );

    // Table data
    const rows = [
      {
        categoria: isPortugueseFlow ? "Servico" : "Service",
        descricao: extractedData.servico || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
      },
      {
        categoria: isPortugueseFlow ? "Contexto" : "Context",
        descricao: extractedData.contexto || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
      },
      {
        categoria: isPortugueseFlow ? "Prazo Solicitado" : "Requested Timeline",
        descricao: extractedData.prazoSolicitado || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
      },
      {
        categoria: isPortugueseFlow ? "Requisitos Especificos" : "Specific Requirements",
        descricao: extractedData.requisitoEspecificos || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
      },
      {
        categoria: isPortugueseFlow ? "Equipa" : "Team",
        descricao: extractedData.equipa || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
      },
      {
        categoria: isPortugueseFlow ? "Financiamento" : "Financing",
        descricao: extractedData.financiamento || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
      },
      {
        categoria: isPortugueseFlow ? "Contacto" : "Contact",
        descricao: extractedData.contacto || (isPortugueseFlow ? "Nao especificado" : "Not specified"),
      },
    ];

    // Table styling
    let currentY = 50;

    // Header
    pdf.setFont("Helvetica", "bold");
    pdf.setFontSize(10);
    pdf.text(isPortugueseFlow ? "Categoria" : "Category", 15, currentY + 8);
    pdf.text(isPortugueseFlow ? "Descricao" : "Description", 70, currentY + 8);
    pdf.line(15, currentY + 12, 200, currentY + 12);
    currentY += 20;

    // Rows
    pdf.setFont("Helvetica", "normal");
    pdf.setFontSize(9);
    rows.forEach((row) => {
      // Check if we need a new page
      if (currentY > 270) {
        pdf.addPage();
        currentY = 20;
      }

      // Category
      pdf.text(row.categoria, 15, currentY);

      // Description (with text wrapping)
      const descriptionLines = pdf.splitTextToSize(row.descricao, 130);
      pdf.text(descriptionLines, 70, currentY);

      // Calculate row height based on content
      const cellHeight = Math.max(10, descriptionLines.length * 6);
      currentY += cellHeight + 5;

      // Row separator
      pdf.line(15, currentY - 5, 200, currentY - 5);
    });

    // Download PDF
    const fileName = `resumo_${extractedData.empresa}.pdf`;
    pdf.save(fileName);
    
    // Also save base64 version for email
    const pdfDataUri = pdf.output("datauristring");
    const base64String = pdfDataUri.split(",")[1];
    setPdfBase64(base64String);
  }, [isPortugueseFlow]);

  const handleGeneratePDF = useCallback(async () => {
    setIsGenerating(true);
    
    try {
      // Try to extract data via API first
      const extractResponse = await fetch("/api/extract-data", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages, isPortugueseFlow }),
      });

      let extractedData: ExtractedData;

      if (extractResponse.ok) {
        // API extraction successful
        const responseData = await extractResponse.json();
        extractedData = responseData.data;
      } else {
        // API failed, use simple local extraction
        console.warn("API extraction failed, using local extraction");
        extractedData = {
          empresa: messages.find((m, i) => m.role === "user" && i > 0 && m.content !== "A" && m.content !== "B")?.content || "Nao especificado",
          servico: messages.find((m) => m.content === "A")
            ? "Consultoria/Assessoria"
            : messages.find((m) => m.content === "B")
            ? "Brainstorming/Ideacao"
            : "Nao especificado",
          contexto: messages.find((m) => m.role === "user" && m.content.length > 50)?.content.slice(0, 200) || "Nao especificado",
          prazoSolicitado: "Nao especificado",
          requisitoEspecificos: "Nao especificado",
          equipa: "Nao especificado",
          financiamento: "Nao especificado",
          contacto: messages[messages.length - 2]?.role === "user" ? messages[messages.length - 2]?.content : "Nao especificado",
        };
      }

      // Generate and download PDF
      await generatePDFDocument(extractedData);

      // Add confirmation message
      const pdfMessage: Message = {
        role: "assistant",
        content: isPortugueseFlow 
          ? "✓ Documento gerado e descarregado com sucesso!" 
          : "✓ Document generated and downloaded successfully!",
      };
      
      if (onAddMessage) {
        onAddMessage(pdfMessage);
      }

      setPdfExtractedData(extractedData);
      
      if (onPDFGenerated) {
        onPDFGenerated(extractedData);
      }
      
      setLocalPdfGenerated(true);
      setIsGenerating(false);
      
      if (onAskedForPDF) {
        onAskedForPDF(false);
      }
    } catch (error) {
      console.error("Error generating PDF:", error);
      const errorMessage: Message = {
        role: "assistant",
        content: isPortugueseFlow 
          ? "Desculpe, houve um erro ao gerar o documento. Tente novamente." 
          : "Sorry, there was an error generating the document. Please try again.",
      };
      
      if (onAddMessage) {
        onAddMessage(errorMessage);
      }
      
      setIsGenerating(false);
    }
  }, [messages, isPortugueseFlow, generatePDFDocument, onPDFGenerated, onAskedForPDF, onAddMessage]);

  const redownloadPDF = useCallback(async () => {
    if (pdfExtractedData) {
      try {
        await generatePDFDocument(pdfExtractedData);
      } catch (error) {
        console.error("Error redownloading PDF:", error);
      }
    }
  }, [pdfExtractedData, generatePDFDocument]);

  // Render PDF confirmation buttons (only if not already generated)
  if (showConfirmation && !localPdfGenerated && !externalPdfGenerated) {
    return (
      <div className="flex flex-col gap-3">
        <div className="flex flex-wrap gap-2 sm:gap-3">
          <button
            onClick={handleGeneratePDF}
            disabled={isGenerating}
            className="rounded-full border border-slate-300 bg-white px-3 sm:px-5 py-1.5 sm:py-2 text-xs sm:text-sm font-medium text-slate-700 transition hover:border-slate-900 hover:text-slate-900 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isGenerating 
              ? (isPortugueseFlow ? "A gerar..." : "Generating...")
              : (isPortugueseFlow ? "Sim, gerar documento" : "Yes, generate document")
            }
          </button>
          <button
            onClick={() => onAskedForPDF?.(false)}
            disabled={isGenerating}
            className="rounded-full border border-slate-300 bg-white px-3 sm:px-5 py-1.5 sm:py-2 text-xs sm:text-sm font-medium text-slate-700 transition hover:border-slate-900 hover:text-slate-900 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isPortugueseFlow ? "Não, continuar a conversar" : "No, keep talking"}
          </button>
        </div>
        
        {isGenerating && (
          <div className="flex flex-col gap-2">
            <div className="text-sm text-slate-600 font-medium">
              {isPortugueseFlow ? "A gerar documento..." : "Generating document..."}
            </div>
            <div className="w-full bg-slate-200 rounded-full h-2 overflow-hidden">
              <div 
                className="bg-indigo-600 h-full rounded-full animate-pulse"
                style={{width: '60%'}}
              ></div>
            </div>
          </div>
        )}
      </div>
    );
  }

  // Render PDF redownload button (shown after PDF is generated)
  if ((localPdfGenerated || externalPdfGenerated) && pdfExtractedData) {
    return (
      <div className="flex flex-col gap-3">
        <div className="flex items-center gap-2">
          <span className="text-green-600 font-semibold">✓</span>
          <span>{isPortugueseFlow ? "Documento gerado e descarregado com sucesso!" : "Document generated and downloaded successfully!"}</span>
        </div>
        <div className="flex gap-2">
          <button
            onClick={redownloadPDF}
            className="flex items-center gap-2 px-3 py-1.5 text-xs sm:text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 rounded-lg transition"
          >
            <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
              <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm3.5-9c.83 0 1.5-.67 1.5-1.5S16.33 8 15.5 8 14 8.67 14 9.5s.67 1.5 1.5 1.5zm-7 0c.83 0 1.5-.67 1.5-1.5S9.33 8 8.5 8 7 8.67 7 9.5 7.67 11 8.5 11zm3.5 6.5c2.33 0 4.31-1.46 5.11-3.5H6.89c.8 2.04 2.78 3.5 5.11 3.5z" />
            </svg>
            {isPortugueseFlow ? "Descarregar PDF" : "Download PDF"}
          </button>
        </div>
        
        {pdfBase64 && (
          <ContactarEmailComponent
            key={currentChatId ?? "email-component"}
            pdfBase64={pdfBase64}
            pdfFileName={`resumo_${pdfExtractedData.empresa}.pdf`}
            isPortugueseFlow={isPortugueseFlow}
            extractedData={pdfExtractedData}
            // pass current chat id so component can prevent duplicate sends per chat
            currentChatId={currentChatId}
            onEmailSent={() => {
              // Optionally add a message to the chat when email sent
              if (onAddMessage) {
                onAddMessage({ role: "assistant", content: isPortugueseFlow ? "Email enviado para a Techlab." : "Email sent to Techlab." });
              }
            }}
          />
        )}
      </div>
    );
  }

  return null;
}
